language: python
python:
    - 2.7
install:
    - pip install -r travis_requirements.txt
before_script:
    - cp vittlify/config/travis.settings vittlify/config/local_settings.py
    - psql -c "create database vittlify;" -U postgres
script:
    - python vittlify/manage.py test vittlify/groceries
