version: '3.4'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - vittlify-data:/var/lib/postgresql/data

  vittlify:
    image: kyokley/vittlify
    build:
      context: .
      target: dev
    depends_on:
      - "postgres"
      - "vittlify-node"
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true

  vittlify-node:
    image: kyokley/vittlify-node
    build:
      context: ./nodejs
      target: vittlify-node
    ports:
      - "3000:3000"

# Persistent Volumes
volumes:
  vittlify-data:
