version: '3.6'

services:
  postgres:
    image: postgres
    volumes:
      - vittlify-data:/var/lib/postgresql/data

  vittlify:
    image: kyokley/vittlify
    build:
      context: .
      target: dev
    depends_on:
      - "postgres"
      - "vittlify-node"
    tty: true
    stdin_open: true

  vittlify-node:
    image: kyokley/vittlify-node
    build:
      context: ./nodejs
      target: vittlify-node

# Persistent Volumes
volumes:
  vittlify-data:
