# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0003_auto_20151224_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceries.Item')),
                ('shopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceries.Shopper')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceries.ShoppingList')),
            ],
        ),
    ]
