# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0005_auto_20151227_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifyaction',
            name='sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
