# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0012_auto_20160202_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='_category',
            field=models.ForeignKey(db_column='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='groceries.ShoppingListCategory'),
        ),
    ]
