# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 23:25
from __future__ import unicode_literals

from django.db import migrations

def move_emails(apps, schema_editor):
    Shopper = apps.get_model('groceries', 'Shopper')

    for shopper in Shopper.objects.all():
        if shopper.email:
            user = shopper.user
            user.email = shopper.email
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0014_shopper_theme'),
    ]

    operations = [
        migrations.RunPython(move_emails),
    ]
