# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0014_shopper_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='SshKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssh_format', models.TextField()),
                ('pem_format', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('shopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceries.Shopper')),
            ],
        ),
    ]
