# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 03:05
from __future__ import unicode_literals

from django.db import migrations, models
from groceries.utils import createToken

def generate_guids(apps, schema_editor):
    Item = apps.get_model('groceries', 'Item')
    for item in Item.objects.all():
        item.guid = createToken()
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0016_item_guid'),
    ]

    operations = [migrations.RunPython(generate_guids),
                  migrations.AlterField(
                      model_name='item',
                      name='guid',
                      field=models.CharField(max_length=32, null=False, unique=True),
                  ),
    ]
