# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import groceries.utils


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0017_auto_20170622_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='guid',
            field=models.CharField(default=groceries.utils.createToken, max_length=32, unique=True),
        ),
    ]
