# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0018_auto_20170622_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshkey',
            name='title',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
