# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0016_remove_shopper_email'),
        ('groceries', '0023_auto_20170625_1426'),
    ]

    operations = [
    ]
