# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0025_auto_20170720_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopper',
            name='email_frequency',
            field=models.CharField(blank=True, choices=[(b'daily', b'Daily'), (b'weekly', b'Weekly'), (None, b'No Emails')], default=b'daily', max_length=6, null=True),
        ),
    ]
