# Generated by Django 3.2.9 on 2022-01-03 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0026_auto_20170720_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='_category',
            field=models.ForeignKey(db_column='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='groceries.shoppinglistcategory'),
        ),
        migrations.AlterField(
            model_name='item',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='notifyaction',
            name='action',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='notifyaction',
            name='shopping_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groceries.shoppinglist'),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='email_frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), (None, 'No Emails')], default='daily', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='theme',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_lists', to='groceries.shopper'),
        ),
        migrations.AlterField(
            model_name='shoppinglistcategory',
            name='name',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('name', 'shopping_list')},
        ),
    ]
