version: '3.4'

services:
  vittlify:
    build:
      context: .
      target: prod
    environment:
      - DB_NAME=changeme
      - DB_USER=changeme
      - DB_HOST=changeme
      - DB_PASSWORD=changeme
      - INTERNAL_NODE_SERVER=http://vittlify-node:3000
      - EXTERNAL_NODE_SERVER=http://localhost:3000
    volumes:
      - ./docker_static:/static
    command:
      /bin/sh -c "/venv/bin/python manage.py collectstatic --noinput --clear && gunicorn -b 0.0.0.0:8000 --access-logfile - --log-file - --error-logfile - config.wsgi:application"

