version: '3.4'

services:
  postgres:
    ports:
      - "127.0.0.1:5432:5432"
    restart: always

  vittlify:
    build:
      context: .
      target: prod
    image: kyokley/vittlify
    environment:
      - DEBUG=false
      - DB_NAME=changeme
      - DB_USER=changeme
      - DB_HOST=changeme
      - DB_PASSWORD=changeme
      - INTERNAL_NODE_SERVER=http://vittlify-node:3000
      - EXTERNAL_NODE_SERVER=http://localhost:3000
    volumes:
      - ./docker_static:/static
    ports:
      - "127.0.0.1:8000:8000"
    command:
      /bin/sh -c "/venv/bin/python manage.py collectstatic --noinput --clear && gunicorn -b 0.0.0.0:8000 --access-logfile - --log-file - --error-logfile - config.wsgi:application"
    restart: always

  vittlify-node:
    build:
      context: ./nodejs
    image: kyokley/vittlify-node
    ports:
      - "127.0.0.1:3000:3000"
    restart: always
