version: '3.4'

services:
  postgres:
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

  vittlify:
    build:
      context: .
      target: dev
    command:
      /bin/sh -c "/venv/bin/python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_HOST=postgres
      - INTERNAL_NODE_SERVER=http://vittlify-node:3000
      - EXTERNAL_NODE_SERVER=http://localhost:3000
    volumes:
      - ./:/code

  vittlify-node:
    volumes:
      - ./nodejs:/code
