version: '3.4'

services:
  postgres:
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "127.0.0.1:5633:5432"

  vittlify:
    build:
      context: .
      target: dev
    command:
      /bin/sh -c "/venv/bin/python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=true
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_HOST=postgres
      - INTERNAL_NODE_SERVER=http://vittlify-node:3000
      - EXTERNAL_NODE_SERVER=http://localhost:3000
    volumes:
      - ./:/code
    ports:
      - "127.0.0.1:8000:8000"

  vittlify-node:
    volumes:
      - ./nodejs:/code
    ports:
      - "127.0.0.1:3000:3000"
