# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0004_notifyaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifyaction',
            name='action',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='notifyaction',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groceries.Item'),
        ),
        migrations.AlterField(
            model_name='notifyaction',
            name='shopping_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groceries.ShoppingList'),
        ),
    ]
