# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import groceries.utils


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0007_auto_20160113_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSocketToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(default=groceries.utils.createToken, max_length=32, unique=True)),
                ('active', models.BooleanField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('shopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceries.Shopper')),
            ],
        ),
    ]
