# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0009_auto_20160121_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingListCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'None', max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='groceries.ShoppingList')),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='shoppinglistcategory',
            unique_together=set([('name', 'shopping_list')]),
        ),
    ]
