# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0010_auto_20160202_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglistcategory',
            options={'ordering': ('date_added',), 'verbose_name_plural': 'Shopping list categories'},
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groceries.ShoppingListCategory'),
        ),
    ]
