# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0019_sshkey_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sshkey',
            unique_together=set([('shopper', 'title')]),
        ),
    ]
