# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0020_auto_20170624_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sshkey',
            name='pem_format',
        ),
    ]
