# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0021_remove_sshkey_pem_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='guid',
            field=models.CharField(null=True, max_length=32, unique=True),
        ),
    ]
