# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 14:26
from __future__ import unicode_literals

from django.db import migrations, models
from groceries.utils import createToken

def generate_guids(apps, schema_editor):
    ShoppingList = apps.get_model('groceries', 'ShoppingList')
    for shopping_list in ShoppingList.objects.all():
        shopping_list.guid = createToken()
        shopping_list.save()

class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0022_shoppinglist_guid'),
    ]

    operations = [migrations.RunPython(generate_guids),
                  migrations.AlterField(
                      model_name='shoppinglist',
                      name='guid',
                      field=models.CharField(max_length=32, null=False, unique=True),
                  ),
                  ]
