name: Test
on:
  pull_request:

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check migrations
      run: make check-migrations

    - name: Run tests
      run: make tests
